#pragma once

// This file contains all the magic numbers.

#define START_PREY_SPEED 150
#define START_PREY_NUMBER 7000
#define START_PREY_COHESION_FORCE 250
#define START_PREY_ALIGNMENT_FORCE 100
#define START_PREY_SEPARATION_FORCE_ 800
#define START_PREY_HUNGER_FORCE 400
#define START_PREY_FEAR_FORCE 500
#define START_PREY_BIG_PERCEPTION_RADIUS 70
#define START_PREY_SMALL_PERCEPTION_RADIUS 40
#define START_PREY_FOOD_PERCEPTION_RADIUS 800
#define START_PREY_DANGER_PERCEPTION_RADIUS 250

#define MIN_PREY_SPEED 15
#define MIN_PREY_NUMBER 10
#define MIN_PREY_COHESION_FORCE 0
#define MIN_PREY_ALIGNMENT_FORCE 0
#define MIN_PREY_SEPARATION_FORCE 0
#define MIN_PREY_HUNGER_FORCE 0
#define MIN_PREY_FEAR_FORCE 0
#define MIN_PREY_BIG_PERCEPTION_RADIUS 10
#define MIN_PREY_SMALL_PERCEPTION_RADIUS 5
#define MIN_PREY_FOOD_PERCEPTION_RADIUS 5
#define MIN_PREY_DANGER_PERCEPTION_RADIUS 10

#define MAX_PREY_SPEED 1000
#define MAX_PREY_NUMBER 20000
#define MAX_PREY_COHESION_FORCE 1500
#define MAX_PREY_ALIGNMENT_FORCE 1500
#define MAX_PREY_SEPARATION_FORCE_ 1500
#define MAX_PREY_HUNGER_FORCE 1500
#define MAX_PREY_FEAR_FORCE 1500
#define MAX_PREY_BIG_PERCEPTION_RADIUS 200
#define MAX_PREY_DANGER_PERCEPTION_RADIUS 250

#define START_PREDATORS_SPEED 130
#define START_PREDATORS_NUMBER 100
#define START_PREDATORS_COHESION_FORCE 100
#define START_PREDATORS_ALIGNMENT_FORCE 100
#define START_PREDATORS_SEPARATION_FORCE 1000
#define START_PREDATORS_HUNGER_FORCE 400
#define START_PREDATORS_BIG_PERCEPTION_RADIUS 200
#define START_PREDATORS_SMALL_PERCEPTION_RADIUS 70
#define START_PREDATORS_FOOD_PERCEPTION_RADIUS 250

#define MIN_PREDATORS_SPEED 15
#define MIN_PREDATORS_NUMBER 1
#define MIN_PREDATORS_COHESION_FORCE 0
#define MIN_PREDATORS_ALIGNMENT_FORCE 0
#define MIN_PREDATORS_SEPARATION_FORCE 0
#define MIN_PREDATORS_HUNGER_FORCE 0
#define MIN_PREDATORS_BIG_PERCEPTION_RADIUS 10
#define MIN_PREDATORS_SMALL_PERCEPTION_RADIUS 5
#define MIN_PREDATORS_FOOD_PERCEPTION_RADIUS 5

#define MAX_PREDATORS_SPEED 1000
#define MAX_PREDATORS_NUMBER 1000
#define MAX_PREDATORS_COHESION_FORCE 1800
#define MAX_PREDATORS_ALIGNMENT_FORCE 1800
#define MAX_PREDATORS_SEPARATION_FORCE 1800
#define MAX_PREDATORS_HUNGER_FORCE 1800
#define MAX_PREDATORS_BIG_PERCEPTION_RADIUS 200

#define START_SIZE_OF_CONTAINER 3000
#define START_CURSOR_DISTANCE 50

#define MIN_SIZE_OF_CONTAINER 200
#define MIN_CURSOR_DISTANCE 50

#define MAX_SIZE_OF_CONTAINER 6000
#define MAX_CURSOR_DISTANCE 1200

#define START_PAUSED 0
#define START_DISPLAY_MODE 0
#define START_RUNNING_ON_CPU 0
#define START_SPHERICAL_CONTAINER 0
#define START_CURSOR_VISIBLE 0
